export { default as AdminPage } from './AdminPage/AdminPage'
export { AnalyticsPage } from './AnalyticsPage/AnalyticsPage'
export { default as CertifyPage } from './CertifyPage/CertifyPage'
export { CopyrightPage } from './CopyrightPage/CopyrightPage'
export { default as CoursesPage } from './CoursesPage/CoursesPage'
export { default as DashboardPage } from './DashboardPage/DashboardPage'
export { default as ExamsPage } from './ExamsPage/ExamsPage'
export { default as MonitorPage } from './MonitorPage/MonitorPage'
export { default as MultisigPage } from './MultisigPage/MultisigPage'
export { default as OrganizationsPage } from './OrganizationsPage/OrganizationsPage'
export { default as ProctoringPage } from './ProctoringPage/ProctoringPage'
export { default as RewardPage } from './RewardPage/RewardPage'
export { default as SecurityPage } from './SecurityPage/SecurityPage'
export { default as TokenManagementPage } from './TokenManagementPage/TokenManagementPage'
export { default as UsersPage } from './UsersPage/UsersPage'
